[package]
name = "rusty-journal"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
serde_json = "1.0.134"
structopt = "0.3.26"
serde = { version = "1.0.217", features = ["derive"] }
home = "0.5.11"
anyhow = "1.0.95"
